# Generated by Django 2.2 on 2019-11-30 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clc_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='verifyregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='isConfirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('expiration', models.DateTimeField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clc_reg.MembershipType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MembershipLevel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
