# Generated by Django 2.2 on 2019-12-04 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clc_reg', '0002_auto_20191130_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField()),
                ('item_purchased', models.CharField(max_length=200)),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PurchaseHistory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillingInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('creditcard', models.CharField(max_length=20)),
                ('expiration_month', models.CharField(max_length=20)),
                ('expiration_year', models.CharField(max_length=20)),
                ('cid', models.CharField(max_length=20)),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BillingInfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
