# Generated by Django 2.2 on 2019-12-04 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clc_reg', '0002_auto_20191130_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField()),
                ('item_purchased', models.CharField(max_length=200)),
                ('expiration_date', models.DateTimeField()),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PurchaseHistory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
